### PR TITLE
feat(circleci): Remove circleci as not needed

### PR DESCRIPTION
**Pull request by Xorima**
circleci was running danger, we have moved this into github actions now so it is no longer required

Signed-off-by: Jason Field <jason@avon-lea.co.uk>

# Description

Describe what this change achieves

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by damacus** [comment]
@Xorima can you push another small commit to test the webhooks please?

**Review by damacus — DISMISSED** [review]

**Comment by Xorima** [comment]
Do not merge, Danger still not working as expected (If you look into the check it says it cannot comment on the PR which is still a problem for us)

**Comment by damacus** [comment]
@Xorima looks like it's working now?

**Comment by Xorima** [comment]
@damacus its not posting it's danger/danger check only the one that runs it

**Comment by damacus** [comment]
> 1 Error
> 🚫	Please include a CHANGELOG entry.
> Generated by 🚫 [Danger](https://danger.systems/)

@Xorima I think it's working now. The permission changes always need to be merge to main before using them. So I did that in the other PR

**Comment by kitchen-porter** [comment]
Released as: [2.0.1](https://github.com/sous-chefs/sc_vscode/releases/tag/2.0.1)

**Pull request merged**
