### PR TITLE
Add unified_mode to resources

### PR DESCRIPTION
**Pull request by bastianschwarz**
# Description

Just added `unified_mode true` to resolve CHEF-33 deprecation

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing. (Covered with cookstyle tests)

### CODE REVIEW

**Comment by MarkGibbons** [comment]
Hello @bastianschwarz, 

It's always good to see a contribution. Thank you for yours.
I'm not a maintainer for this project but I've done a few of these updates.
Could you change the chef_version supported in metadata to >= 15.3?
Also a comment in the Unreleased section of the changelog would probably be appreciated.

Regards, Mark

**Comment by bastianschwarz** [comment]
I guess the delivery action fails because actionshub/chef-delivery should now use @main but it seems to be behind master? Not sure if I should change this in this PR ... probably not?

**Comment by MarkGibbons** [comment]
@bastianschwarz I get the same messages about @main in projects I contribute to. I don't think that has anything to do with the failure.  I hope @xorima or @ramereth can explain the delivery issue. I don't think your PR is responsible for that issue.

**Review by MarkGibbons — DISMISSED** [review]

**Comment by ramereth** [comment]
@bastianschwarz can you please rebase again? I think that will fix the remaining issue.

**Comment by bastianschwarz** [comment]
So ... not sure what to make of the build error since it works in some instances? Also the actual error is not in the logs since it seems that the command just didn't return 0.

I don't think this is related to unified_mode

How to proceed with this?

**Comment by bmhughes** [comment]
Add some temporary debug code into get the stdout/stderr for the command to see why it's failing would be my first port of call. Shouldn't be too diffcult to add a `Chef::Log.warn` to the stdout and stderr properties of the shellout object in the library that does the work.

**Pull request closed without merging**
